# Generated by Django 5.1.3 on 2025-02-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at', '-priority']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
