# Generated by Django 5.1.3 on 2025-02-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_friendrequest_friendship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
