# Generated by Django 5.1.3 on 2025-02-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_task_options_remove_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('task_created', 'タスク作成'), ('task_completed', 'タスク完了'), ('level_up', 'レベルアップ'), ('friend_added', '友達追加')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'タイムラインアクティビティ',
                'verbose_name_plural': 'タイムラインアクティビティ',
                'ordering': ['-created_at'],
            },
        ),
    ]
