# Generated by Django 5.1.3 on 2025-02-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser_experience_points_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
