# Generated by Django 5.1.3 on 2025-02-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', '未着手'), ('in_progress', '進行中'), ('completed', '完了')], default='not_started', max_length=20),
        ),
    ]
